name: wordle_assist
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - libcxx=12.0.1
  - libffi=3.3
  - libzlib=1.2.11
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=22.0.3
  - pytest=7.0.1
  - python=3.9.7
  - python_abi=3.9
  - readline=8.1
  - setuptools=60.9.3
  - sqlite=3.37.0
  - tk=8.6.12
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
